### ISSUE TITLE
Scope new datasets

### ISSUE THREAD

**Issue by Juan-Mateos** [EURITO/Pivot#12]
Some examples:
* GitHub [See nestauk/data-triage#1]
* Vaccines [See nestauk/data-triage#1]
* Open datasets about Covid
* .... [See comments below from Agzam]

**Comment by porter22** [comment]
- OpenAIRE data of publications, datasets, software tools
- Drugbank data of drugs, their approval status, targeted proteins. I did some Kaggle exploration and visualisation of the dataset [here](https://www.kaggle.com/idrissov22/cord-19-visualisation-of-drug-characteristics.).
- CORD-19 data in general. Link [here](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge)

**Comment by porter22** [comment]
Elsevier has just opened up a bunch of COVID datasets and tools:
[](https://www.elsevier.com/clinical-solutions/coronavirus-research-hub?dgcid=RN_AGCM_Program_300005088)

**Comment by jaklinger** [comment]
Closing, in response to nestauk/data-triage#1
