### ISSUE TITLE
23b_arxiv: 2003 can't connect to mysql server on

### ISSUE THREAD

**Issue by Juan-Mateos** [EURITO/Pivot#45]
When I run `python indicators/two/make_topics.py` I get

`sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'innovation-mapping-mysql-mysql5721.ci9272ypsbyf.eu-west-2.rds.amazonaws.com' (timed out)")`

NB I have decrypted `mysqldb.config`

**Comment by jaklinger** [comment]
This looks like a VPN issue

**Comment by Juan-Mateos** [comment]
Ah FFS I keep forgetting to connect to VPN. Sorry!!
